# Generated by Django 5.1.1 on 2024-09-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'news', 'verbose_name_plural': 'newses'},
        ),
    ]
